lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [     # we can trim down to only include the latter part of our three URLs
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),      # (\d+) - capture group -> will be passed to the view as an argument
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),        # include take a part of a URL regex as a prefix, which will be applied to all the includeed URLs (so we can reduce dupication)
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):                   # classes that inherit from models.Model map to tables in the database (ang get auto-generated id attribute -> primary key column in the database)
    text = models.TextField(default='')     # any other column must be defined explicitly(with default value):  this is a text field
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django.core.exceptions import ValidationError
from django import forms
from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):
    
    class Meta:
        model = Item                    # specify for which model id the form
        fields = ('text',)              # specify which fields we want it to use
        widgets = {
                'text': forms.fields.TextInput(attrs={
                    'placeholder': 'Enter a to-do item',
                    'class': 'form-control input-lg',
                }),
        }
        error_messages = {
                'text': {'required': EMPTY_ITEM_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list   # .instance attribute on a form represents the databse object that is being modified or created
        return super().save()

class ExistingListItemForm(ItemForm):
    
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render
from lists.forms import ExistingListItemForm, ItemForm
from lists.models import Item, List

def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)                                          # redirect uses 'get_absolute_url' from List model automatically
    return render(request, 'list.html', {'list': list_, "form": form})

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form": form})

lists/templates/base.html
<!DOCTYPE html>
<html land="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>To-Do lists</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base.css" rel="stylesheet">
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron">	<!-- Embiggen the main page header and the input form with 'jumbotron' -->
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock %}">
							{{ form.text }}		<!-- Renders just the HTML input for the text field of the form. -->
							{% csrf_token %}	<!-- Add auto-generated token in each form to be able to identify POST requests as having come from the original site. -->
										<!-- Django will substitute that during rendering with an <input type="hidden"> containing CSRF token. -->
							{% if form.errors %}
								<div class="form-group has-error">
									<div class="help-block">{{ form.text.errors }}</div>
								</div>
							{% endif %}
						</form>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					{% block table %}
					{% endblock %}
				</div>
			</div>
		</div>
		<script src="/static/jquery-3.2.1.js"></script>
		<script src="/static/list.js"></script>

		<script>
			$(document).ready(function () {
			  window.Superlists.initialize();
			});
		</script>
	</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
	<table id="id_list_table" class="table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}